-- MySQL Script generated by MySQL Workbench
-- Seg 15 Jan 2018 17:42:15 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema admin_framework
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admin_framework
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin_framework` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `admin_framework` ;

-- -----------------------------------------------------
-- Table `admin_framework`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`modules` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `control_class` VARCHAR(100) NOT NULL,
  `db_name` VARCHAR(100) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`unities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`unities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `unities_id` INT UNSIGNED NULL,
  `remember_token` VARCHAR(100) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_unities1_idx` (`unities_id` ASC),
  CONSTRAINT `fk_users_unities1`
    FOREIGN KEY (`unities_id`)
    REFERENCES `admin_framework`.`unities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`contact_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`contact_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`contacts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `contact_types_id` INT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_users1_idx` (`users_id` ASC),
  INDEX `fk_contacts_contact_types1_idx` (`contact_types_id` ASC),
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `admin_framework`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacts_contact_types1`
    FOREIGN KEY (`contact_types_id`)
    REFERENCES `admin_framework`.`contact_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`module_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`module_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modules_id` INT UNSIGNED NOT NULL,
  `groups_id` INT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_module_groups_modules1_idx` (`modules_id` ASC),
  INDEX `fk_module_groups_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_module_groups_modules1`
    FOREIGN KEY (`modules_id`)
    REFERENCES `admin_framework`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_groups_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `admin_framework`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`log_accesses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`log_accesses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`password_resets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_framework`.`user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`user_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `groups_id` INT UNSIGNED NOT NULL,
  `updated_at` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_groups_users1_idx` (`users_id` ASC),
  INDEX `fk_user_groups_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_user_groups_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `admin_framework`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_groups_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `admin_framework`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `admin_framework` ;

-- -----------------------------------------------------
-- Placeholder table for view `admin_framework`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_framework`.`user_details` (`name` INT, `email` INT, `status` INT);

-- -----------------------------------------------------
-- View `admin_framework`.`user_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_framework`.`user_details`;
USE `admin_framework`;
CREATE  OR REPLACE VIEW `user_details` AS
    SELECT 
        `us`.`name`,
        `us`.`email`,
        `us`.`status`,
        `gr`.`name`,
        `un`.`name`
    FROM
        `users` AS `us`,
        `user_groups` AS `ug`,
        `groups` AS `gr`,
        `unities` AS `un`
    WHERE
        `us`.`id` = `ug`.`users_id`
            AND `us`.`unities_id` = `un`.`id`
            AND `gr`.`id` = `ug`.`groups_id`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
